"""Seed IPL 2026 squads from official NDTV/BCCI data (post mega auction + trades)."""
import asyncio
import os
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

SQUADS = [
    {
        "teamName": "Chennai Super Kings",
        "teamShort": "CSK",
        "captain": "Ruturaj Gaikwad",
        "players": [
            {"name": "Ruturaj Gaikwad", "role": "Batsman", "isCaptain": True, "isOverseas": False},
            {"name": "MS Dhoni", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Sanju Samson", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Ayush Mhatre", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Sarfaraz Khan", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Shivam Dube", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Ramakrishna Ghosh", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Shreyas Gopal", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Aman Khan", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Urvil Patel", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Kartik Sharma", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Prashant Veer", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Anshul Kamboj", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Khaleel Ahmed", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mukesh Choudhary", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Gurjapneet Singh", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Rahul Chahar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Dewald Brevis", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Jamie Overton", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Nathan Ellis", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Noor Ahmad", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Matt Henry", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Matthew Short", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Akeal Hosein", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Zakary Foulkes", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
        ],
    },
    {
        "teamName": "Mumbai Indians",
        "teamShort": "MI",
        "captain": "Hardik Pandya",
        "players": [
            {"name": "Hardik Pandya", "role": "All-rounder", "isCaptain": True, "isOverseas": False},
            {"name": "Rohit Sharma", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Suryakumar Yadav", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Tilak Varma", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Naman Dhir", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Robin Minz", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Raj Angad Bawa", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Ashwani Kumar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Deepak Chahar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Raghu Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Shardul Thakur", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Mayank Markande", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Ryan Rickelton", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Jasprit Bumrah", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Trent Boult", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Mitchell Santner", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Corbin Bosch", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Will Jacks", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Allah Ghazanfar", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Sherfane Rutherford", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Quinton de Kock", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Mohammad Izhar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Danish Malewar", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Atharva Ankolekar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Mayank Rawat", "role": "Batsman", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Royal Challengers Bengaluru",
        "teamShort": "RCB",
        "captain": "Rajat Patidar",
        "players": [
            {"name": "Rajat Patidar", "role": "Batsman", "isCaptain": True, "isOverseas": False},
            {"name": "Virat Kohli", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Devdutt Padikkal", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Jitesh Sharma", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Krunal Pandya", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Swapnil Singh", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Venkatesh Iyer", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Bhuvneshwar Kumar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Yash Dayal", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Rasikh Salam", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Suyash Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Abhinandan Singh", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mangesh Yadav", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Kanishk Chouhan", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Vicky Ostwal", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Phil Salt", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Tim David", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Jacob Bethell", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Romario Shepherd", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Josh Hazlewood", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Nuwan Thushara", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Jacob Duffy", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Jordan Cox", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Satwik Deswal", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Vihaan Malhotra", "role": "Batsman", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Kolkata Knight Riders",
        "teamShort": "KKR",
        "captain": "Ajinkya Rahane",
        "players": [
            {"name": "Ajinkya Rahane", "role": "Batsman", "isCaptain": True, "isOverseas": False},
            {"name": "Rinku Singh", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Angkrish Raghuvanshi", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Manish Pandey", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Ramandeep Singh", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Anukul Roy", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Varun Chakaravarthy", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Vaibhav Arora", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Harshit Rana", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Umran Malik", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Prashant Solanki", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Kartik Tyagi", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Akash Deep", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Daksh Kamra", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Sarthak Ranjan", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Sunil Narine", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Rovman Powell", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Cameron Green", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Matheesha Pathirana", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Mustafizur Rahman", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Finn Allen", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Tim Seifert", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Rachin Ravindra", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Tejasvi Singh", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Rahul Tripathi", "role": "Batsman", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Sunrisers Hyderabad",
        "teamShort": "SRH",
        "captain": "Pat Cummins",
        "players": [
            {"name": "Pat Cummins", "role": "Bowler", "isCaptain": True, "isOverseas": True},
            {"name": "Travis Head", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Abhishek Sharma", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Ishan Kishan", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Nitish Kumar Reddy", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Harsh Dubey", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Harshal Patel", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Jaydev Unadkat", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Eshan Malinga", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Zeeshan Ansari", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Aniket Verma", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "R. Smaran", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Heinrich Klaasen", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Kamindu Mendis", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Brydon Carse", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Liam Livingstone", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Jack Edwards", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Salil Arora", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Shivang Kumar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Sakib Hussain", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Onkar Tarmale", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Krains Fuletra", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Praful Hinge", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Amit Kumar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Shivam Mavi", "role": "Bowler", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Rajasthan Royals",
        "teamShort": "RR",
        "captain": "Riyan Parag",
        "players": [
            {"name": "Riyan Parag", "role": "All-rounder", "isCaptain": True, "isOverseas": False},
            {"name": "Yashasvi Jaiswal", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Dhruv Jurel", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Vaibhav Suryavanshi", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Shubham Dubey", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Ravindra Jadeja", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Yudhvir Singh Charak", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Tushar Deshpande", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Ravi Singh", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Sushant Mishra", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Kuldeep Sen", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Ravi Bishnoi", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Shimron Hetmyer", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Jofra Archer", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Sam Curran", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Kwena Maphaka", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Nandre Burger", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Lhuan-Dre Pretorius", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Adam Milne", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Donovan Ferreira", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Vignesh Puthur", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Yash Raj Punja", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Aman Rao", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Brijesh Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Sandeep Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Punjab Kings",
        "teamShort": "PBKS",
        "captain": "Shreyas Iyer",
        "players": [
            {"name": "Shreyas Iyer", "role": "Batsman", "isCaptain": True, "isOverseas": False},
            {"name": "Prabhsimran Singh", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Priyansh Arya", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Shashank Singh", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Nehal Wadhera", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Musheer Khan", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Harpreet Brar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Suryansh Shedge", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Arshdeep Singh", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Yuzvendra Chahal", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Vyshak Vijaykumar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Yash Thakur", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Vishnu Vinod", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Harnoor Pannu", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Pyala Avinash", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Marcus Stoinis", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Azmatullah Omarzai", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Marco Jansen", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Lockie Ferguson", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Xavier Bartlett", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Mitchell Owen", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Cooper Connolly", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Ben Dwarshuis", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Praveen Dubey", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Vishal Nishad", "role": "Bowler", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Gujarat Titans",
        "teamShort": "GT",
        "captain": "Shubman Gill",
        "players": [
            {"name": "Shubman Gill", "role": "Batsman", "isCaptain": True, "isOverseas": False},
            {"name": "Sai Sudharsan", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Shahrukh Khan", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Rahul Tewatia", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Washington Sundar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Nishant Sindhu", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Jayant Yadav", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Manav Suthar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mohammed Siraj", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Prasidh Krishna", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Ishant Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Arshad Khan", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Sai Kishore", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Gurnoor Singh Brar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Kumar Kushagra", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Anuj Rawat", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Jos Buttler", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Rashid Khan", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Kagiso Rabada", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Glenn Phillips", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Jason Holder", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Tom Banton", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Luke Wood", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Ashok Sharma", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Prithvi Raj Yarra", "role": "Bowler", "isCaptain": False, "isOverseas": False},
        ],
    },
    {
        "teamName": "Lucknow Super Giants",
        "teamShort": "LSG",
        "captain": "Rishabh Pant",
        "players": [
            {"name": "Rishabh Pant", "role": "Wicketkeeper", "isCaptain": True, "isOverseas": False},
            {"name": "Ayush Badoni", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Himmat Singh", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Abdul Samad", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Shahbaz Ahmed", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Arshin Kulkarni", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Mayank Yadav", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Avesh Khan", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mohammed Shami", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mohsin Khan", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Manimaran Siddharth", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Digvesh Rathi", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Prince Yadav", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Akash Singh", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Arjun Tendulkar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Akshat Raghuwanshi", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Naman Tiwari", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Mukul Choudhary", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Nicholas Pooran", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Aiden Markram", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Mitchell Marsh", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Josh Inglis", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": True},
            {"name": "Anrich Nortje", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Wanindu Hasaranga", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Matthew Breetzke", "role": "Batsman", "isCaptain": False, "isOverseas": True},
        ],
    },
    {
        "teamName": "Delhi Capitals",
        "teamShort": "DC",
        "captain": "Axar Patel",
        "players": [
            {"name": "Axar Patel", "role": "All-rounder", "isCaptain": True, "isOverseas": False},
            {"name": "KL Rahul", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Karun Nair", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Sameer Rizvi", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Ashutosh Sharma", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Abhishek Porel", "role": "Wicketkeeper", "isCaptain": False, "isOverseas": False},
            {"name": "Vipraj Nigam", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Madhav Tiwari", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Tripurana Vijay", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Ajay Mandal", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Nitish Rana", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
            {"name": "Kuldeep Yadav", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "T. Natarajan", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Mukesh Kumar", "role": "Bowler", "isCaptain": False, "isOverseas": False},
            {"name": "Prithvi Shaw", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Sahil Parakh", "role": "Batsman", "isCaptain": False, "isOverseas": False},
            {"name": "Mitchell Starc", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Tristan Stubbs", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Dushmantha Chameera", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Pathum Nissanka", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Ben Duckett", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "David Miller", "role": "Batsman", "isCaptain": False, "isOverseas": True},
            {"name": "Lungi Ngidi", "role": "Bowler", "isCaptain": False, "isOverseas": True},
            {"name": "Kyle Jamieson", "role": "All-rounder", "isCaptain": False, "isOverseas": True},
            {"name": "Auqib Nabi Dar", "role": "All-rounder", "isCaptain": False, "isOverseas": False},
        ],
    },
]


async def seed():
    mongo_url = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
    db_name = os.environ.get("DB_NAME", "test_database")
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]

    now = datetime.now(timezone.utc).isoformat()

    # Drop old squads and insert fresh
    await db.ipl_squads.delete_many({})

    for squad in SQUADS:
        squad["loadedAt"] = now
        squad["source"] = "NDTV/BCCI Official - Post Mega Auction Dec 2025"
        await db.ipl_squads.insert_one(squad)

    count = await db.ipl_squads.count_documents({})
    print(f"Seeded {count} IPL 2026 squads successfully!")

    # Verify a couple
    csk = await db.ipl_squads.find_one({"teamShort": "CSK"}, {"_id": 0, "players": {"$slice": 3}})
    print(f"  CSK captain: {csk['captain']}, first 3: {[p['name'] for p in csk['players'][:3]]}")
    rcb = await db.ipl_squads.find_one({"teamShort": "RCB"}, {"_id": 0, "players": {"$slice": 3}})
    print(f"  RCB captain: {rcb['captain']}, first 3: {[p['name'] for p in rcb['players'][:3]]}")


if __name__ == "__main__":
    asyncio.run(seed())
